# Generated by Django 5.1.2 on 2026-02-28 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('drawing_data', models.JSONField(default=dict, help_text='Canvas stroke data en JSON')),
                ('image_url', models.URLField(blank=True, default='')),
                ('cloudinary_id', models.CharField(blank=True, default='', help_text='public_id en Cloudinary para poder borrarla', max_length=255)),
                ('color', models.CharField(blank=True, default='#3b82f6', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fishes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
