# Generated by Django 5.1.2 on 2026-02-21 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_display', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('zoom_inicial', models.PositiveSmallIntegerField(default=15)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'ordering': ['nombre_display'],
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokedex_id', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.URLField(blank=True, max_length=500)),
                ('imagen_shiny', models.URLField(blank=True, max_length=500)),
                ('is_shiny', models.BooleanField(default=False)),
                ('hp', models.PositiveSmallIntegerField(default=0)),
                ('attack', models.PositiveSmallIntegerField(default=0)),
                ('defense', models.PositiveSmallIntegerField(default=0)),
                ('special_attack', models.PositiveSmallIntegerField(default=0)),
                ('special_defense', models.PositiveSmallIntegerField(default=0)),
                ('speed', models.PositiveSmallIntegerField(default=0)),
                ('rareza', models.CharField(choices=[('comun', 'Común'), ('raro', 'Raro'), ('epico', 'Épico'), ('legendario', 'Legendario')], default='comun', max_length=20)),
                ('habilidades', models.ManyToManyField(blank=True, to='game.habilidad')),
                ('tipos', models.ManyToManyField(blank=True, to='game.tipo')),
            ],
            options={
                'verbose_name': 'Pokémon',
                'ordering': ['pokedex_id'],
            },
        ),
        migrations.CreateModel(
            name='PokemonLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi_nombre', models.CharField(blank=True, help_text='Nombre del POI en OSM', max_length=200)),
                ('poi_tipo', models.CharField(choices=[('plaza', 'Plaza'), ('parque', 'Parque'), ('monumento', 'Monumento'), ('farmacia', 'Farmacia'), ('fuente', 'Fuente'), ('biblioteca', 'Biblioteca'), ('museo', 'Museo'), ('teatro', 'Teatro'), ('iglesia', 'Iglesia'), ('mercado', 'Mercado'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('poi_osm_id', models.BigIntegerField(blank=True, help_text='ID del elemento en OpenStreetMap', null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radio_metros', models.PositiveSmallIntegerField(default=80)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='game.ciudad')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='game.pokemon')),
            ],
            options={
                'verbose_name': 'Ubicación de Pokémon',
                'verbose_name_plural': 'Ubicaciones de Pokémon',
                'unique_together': {('pokemon', 'poi_osm_id')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField(blank=True)),
                ('puntos', models.PositiveIntegerField(default=0)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.ciudad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
            },
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capturado_en', models.DateTimeField(auto_now_add=True)),
                ('lat_captura', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon_captura', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.pokemonlocation')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.pokemon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coleccion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-capturado_en'],
                'unique_together': {('user', 'location')},
            },
        ),
    ]
