# Generated by Django 5.1.2 on 2026-02-19 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('specialty', models.CharField(blank=True, max_length=100, verbose_name='Especialidad')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía corta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Dentista',
                'verbose_name_plural': 'Dentistas',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=25, verbose_name='Teléfono')),
                ('notes', models.TextField(blank=True, verbose_name='Notas del historial')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Servicio')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Debe ser múltiplo de 30. Bloquea los slots necesarios en la agenda.', verbose_name='Duración (min)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio')),
                ('color', models.CharField(default='#2d9e94', max_length=7, verbose_name='Color hex')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('dentist', models.ForeignKey(blank=True, help_text='Vacío = bloquea todo el consultorio ese día.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='appointments.dentist', verbose_name='Dentista')),
            ],
            options={
                'verbose_name': 'Fecha bloqueada',
                'verbose_name_plural': 'Fechas bloqueadas',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='dentist',
            name='services',
            field=models.ManyToManyField(related_name='dentists', to='appointments.service', verbose_name='Servicios que realiza'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora inicio')),
                ('end_time', models.TimeField(editable=False, verbose_name='Hora fin')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no_show', 'No se presentó')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Notas del paciente')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('confirmation_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.dentist')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.service')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día')),
                ('start_time', models.TimeField(verbose_name='Inicio franja 1')),
                ('end_time', models.TimeField(verbose_name='Fin franja 1')),
                ('start_time_2', models.TimeField(blank=True, help_text='Opcional. Rellena solo si hay horario partido (p.ej. tarde de invierno: 16:00).', null=True, verbose_name='Inicio franja 2')),
                ('end_time_2', models.TimeField(blank=True, help_text='Opcional. Rellena solo si hay horario partido (p.ej. tarde de invierno: 20:00).', null=True, verbose_name='Fin franja 2')),
                ('is_active', models.BooleanField(default=True)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='appointments.dentist')),
            ],
            options={
                'verbose_name': 'Horario de trabajo',
                'verbose_name_plural': 'Horarios de trabajo',
                'ordering': ['dentist', 'day_of_week'],
                'unique_together': {('dentist', 'day_of_week')},
            },
        ),
    ]
